# Generated by Django 3.2.9 on 2021-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
